services:
  sistemadeponto.api:
    image: ${DOCKER_REGISTRY-}sistemadepontoapi
    build:
      context: .
      dockerfile: SistemaDePonto/Dockerfile  
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: